function regressionEnsemble=runTrees(predictors,response,hyper)
%run ens. trees
%input:
%predictors - n x m matrix of predictors
%response - n x 1 vector of responses
%hyper - structrue of hyperparameters w/ fields:
%MaxNumSplits,Method,MinLeafSize,NumLearningCycles,NumVariablesToSample,and
%Learnrate (if Method = 'LSBoost')

template = templateTree('MinLeafSize',hyper.MinLeafSize,...
    'NumVariablesToSample',hyper.NumVariablesToSample,...
    'MaxNumSplits',hyper.MaxNumSplits);

switch hyper.Method
    case 'Bag'
        regressionEnsemble = fitrensemble(...
            predictors, ...
            response, ...
            'Method', hyper.Method, ...
            'NumLearningCycles',hyper.NumLearningCycles,...
            'Learners', template,'NPrint',5);
    case 'LSBoost'
        regressionEnsemble = fitrensemble(...
            predictors, ...
            response, ...
            'Method', hyper.Method, ...
            'NumLearningCycles',hyper.NumLearningCycles,'LearnRate',hyper.LearnRate,...
            'Learners', template,'NPrint',5);
end